---
  - name: Get route info
    hosts: all
    tasks:
      # - name: debug
      #   ansible.builtin.debug:
      #     var: "{{ hostvars[groups['all'][0]] }}"
      - name: Install all updates
        ansible.builtin.apt:
          name: "*"
          cache_valid_time: 3600
          update_cache: true
          state: latest
      - name: Install dependencies
        ansible.builtin.apt:
          pkg:
            - software-properties-common
      - name: Add Ansible Repository
        ansible.builtin.apt_repository:
          repo: ppa:ansible/ansible
          state: present
      - name: Install Ansible
        ansible.builtin.apt:
          update_cache: true
          pkg:
            - ansible
            - git
            - python3-boto3