---
  - name: Get storage info
    hosts: all
    vars_files:
      - ../vars/windows.yml
    #connection: local
    #gather_facts: true
    tasks:
      - name: Show EC2 volume info
        ansible.builtin.debug:
          msg: "{{ inventory_hostname }}"
        delegate_to: localhost
      - name: Get EC2 instance info
        amazon.aws.ec2_instance_info:
          filters:
            "tag:Name": "{{ inventory_hostname }}"
            instance-state-name: ["running"]
          region: "{{ hostvars[inventory_hostname].placement.region }}"
        register: ec2_instance
        delegate_to: localhost
      - name: Show EC2 instance info
        ansible.builtin.debug:
          msg: "{{ ec2_instance.instances[0].instance_id }}"
        delegate_to: localhost
      - name: Make sure one instance was returned
        ansible.builtin.fail:
          msg: "No instance found for {{ inventory_hostname }}"
        when: ec2_instance.instances | length == 0 or ec2_instance.instances | length > 1
        delegate_to: localhost
      - name: Gather EC2 volume info
        amazon.aws.ec2_vol_info:
          filters:
            attachment.instance_id: "{{ ec2_instance.instances[0].instance_id }}"
          region: "{{ hostvars[inventory_hostname].placement.region }}"
        register: ec2_vol_info
        delegate_to: localhost
      - name: Show EC2 volume info
        ansible.builtin.debug:
          msg: "{{ ec2_vol_info }}"
        delegate_to: localhost
      - name: Get disk facts
        community.windows.win_disk_facts:
        register: windows_disks
      - name: Show disk information
        ansible.builtin.debug:
          msg: "{{ windows_disks }}"