storage_safe_mode: true # set to false when resizing PVs
storage_layout:
- name: epic
  grow_to_fill: false # set to true when resizing PVs
  type: lvm
  disks:
    - disk1
    - disk2
    - disk3
  volumes:
    - name: shared
      size: "80g"
      raid_level: striped
      mount_point: "/epic"
      fs_type: xfs
      state: present
- name: db
  disks:
    - disk4
  volumes:
    - name: users
      size: "20g"
      fs_type: xfs
      state: present
      mount_point: "/mnt/app/users"